### ISSUE TITLE
weird error on linux

### ISSUE THREAD

**Issue by norbit8** [mattany/panopto-link-generator#1]
So I get the following error, I know I'm using vevn, but I also treid running it in normal mode, and got the same results.

```
Traceback (most recent call last):
  File "linux_version.py", line 57, in <module>
    download_file(LINK, output)
  File "linux_version.py", line 23, in download_file
    driver = webdriver.Firefox(executable_path=firefoxPath)
  File "/home/mercydude/anaconda3/envs/main/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/mercydude/anaconda3/envs/main/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/mercydude/anaconda3/envs/main/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /home/mercydude/firefox/firefox unexpectedly exited. Status code was: 0
```

**Comment by norbit8** [comment]
Here is the same error not using vevn
```
Traceback (most recent call last):
  File "linux_version.py", line 57, in <module>
    download_file(LINK, output)
  File "linux_version.py", line 23, in download_file
    driver = webdriver.Firefox(executable_path=firefoxPath)
  File "/home/mercydude/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/mercydude/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/mercydude/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /home/mercydude/firefox/firefox unexpectedly exited. Status code was: 0

```

**Comment by mattany** [comment]
Set the firefox path variable to point to the geckodriver executable on your system
